export const countries = [
    // {
    //     code: "BD",
    //     dial_code: "+880",
    //     name: "Bangladesh",
    //     flag: "https://flagcdn.com/w20/bd.png",
    //     phoneLength: 10,
    // },
    {
        code: "US",
        dial_code: "+1",
        name: "United States",
        flag: "https://flagcdn.com/w20/us.png",
        phoneLength: 10,
    },
    {
        code: "GB",
        dial_code: "+44",
        name: "United Kingdom",
        flag: "https://flagcdn.com/w20/gb.png",
        phoneLength: 10,
    },
    {
        code: "IN",
        dial_code: "+91",
        name: "India",
        flag: "https://flagcdn.com/w20/in.png",
        phoneLength: 10,
    },
    {
        code: "AU",
        dial_code: "+61",
        name: "Australia",
        flag: "https://flagcdn.com/w20/au.png",
        phoneLength: 9,
    },
    {
        code: "DE",
        dial_code: "+49",
        name: "Germany",
        flag: "https://flagcdn.com/w20/de.png",
        phoneLength: 10,
    },
    {
        code: "FR",
        dial_code: "+33",
        name: "France",
        flag: "https://flagcdn.com/w20/fr.png",
        phoneLength: 9,
    },
    {
        code: "CA",
        dial_code: "+1",
        name: "Canada",
        flag: "https://flagcdn.com/w20/ca.png",
        phoneLength: 10,
    },
    // {
    //     code: "JP",
    //     dial_code: "+81",
    //     name: "Japan",
    //     flag: "https://flagcdn.com/w20/jp.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "CN",
    //     dial_code: "+86",
    //     name: "China",
    //     flag: "https://flagcdn.com/w20/cn.png",
    //     phoneLength: 11,
    // },
    // {
    //     code: "BR",
    //     dial_code: "+55",
    //     name: "Brazil",
    //     flag: "https://flagcdn.com/w20/br.png",
    //     phoneLength: 11,
    // },
    // {
    //     code: "RU",
    //     dial_code: "+7",
    //     name: "Russia",
    //     flag: "https://flagcdn.com/w20/ru.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "ZA",
    //     dial_code: "+27",
    //     name: "South Africa",
    //     flag: "https://flagcdn.com/w20/za.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "NG",
    //     dial_code: "+234",
    //     name: "Nigeria",
    //     flag: "https://flagcdn.com/w20/ng.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "MX",
    //     dial_code: "+52",
    //     name: "Mexico",
    //     flag: "https://flagcdn.com/w20/mx.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "IT",
    //     dial_code: "+39",
    //     name: "Italy",
    //     flag: "https://flagcdn.com/w20/it.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "ES",
    //     dial_code: "+34",
    //     name: "Spain",
    //     flag: "https://flagcdn.com/w20/es.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "AR",
    //     dial_code: "+54",
    //     name: "Argentina",
    //     flag: "https://flagcdn.com/w20/ar.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "SA",
    //     dial_code: "+966",
    //     name: "Saudi Arabia",
    //     flag: "https://flagcdn.com/w20/sa.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "KR",
    //     dial_code: "+82",
    //     name: "South Korea",
    //     flag: "https://flagcdn.com/w20/kr.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "TR",
    //     dial_code: "+90",
    //     name: "Turkey",
    //     flag: "https://flagcdn.com/w20/tr.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "EG",
    //     dial_code: "+20",
    //     name: "Egypt",
    //     flag: "https://flagcdn.com/w20/eg.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "SE",
    //     dial_code: "+46",
    //     name: "Sweden",
    //     flag: "https://flagcdn.com/w20/se.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "CH",
    //     dial_code: "+41",
    //     name: "Switzerland",
    //     flag: "https://flagcdn.com/w20/ch.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "NL",
    //     dial_code: "+31",
    //     name: "Netherlands",
    //     flag: "https://flagcdn.com/w20/nl.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "AE",
    //     dial_code: "+971",
    //     name: "United Arab Emirates",
    //     flag: "https://flagcdn.com/w20/ae.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "SG",
    //     dial_code: "+65",
    //     name: "Singapore",
    //     flag: "https://flagcdn.com/w20/sg.png",
    //     phoneLength: 8,
    // },
    // {
    //     code: "NZ",
    //     dial_code: "+64",
    //     name: "New Zealand",
    //     flag: "https://flagcdn.com/w20/nz.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "PK",
    //     dial_code: "+92",
    //     name: "Pakistan",
    //     flag: "https://flagcdn.com/w20/pk.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "ID",
    //     dial_code: "+62",
    //     name: "Indonesia",
    //     flag: "https://flagcdn.com/w20/id.png",
    //     phoneLength: 11,
    // },
    // {
    //     code: "TH",
    //     dial_code: "+66",
    //     name: "Thailand",
    //     flag: "https://flagcdn.com/w20/th.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "PH",
    //     dial_code: "+63",
    //     name: "Philippines",
    //     flag: "https://flagcdn.com/w20/ph.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "MY",
    //     dial_code: "+60",
    //     name: "Malaysia",
    //     flag: "https://flagcdn.com/w20/my.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "VN",
    //     dial_code: "+84",
    //     name: "Vietnam",
    //     flag: "https://flagcdn.com/w20/vn.png",
    //     phoneLength: 10,
    // },
    // {
    //     code: "PL",
    //     dial_code: "+48",
    //     name: "Poland",
    //     flag: "https://flagcdn.com/w20/pl.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "BE",
    //     dial_code: "+32",
    //     name: "Belgium",
    //     flag: "https://flagcdn.com/w20/be.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "IL",
    //     dial_code: "+972",
    //     name: "Israel",
    //     flag: "https://flagcdn.com/w20/il.png",
    //     phoneLength: 9,
    // },
    // {
    //     code: "NO",
    //     dial_code: "+47",
    //     name: "Norway",
    //     flag: "https://flagcdn.com/w20/no.png",
    //     phoneLength: 8,
    // },
    // {
    //     code: "DK",
    //     dial_code: "+45",
    //     name: "Denmark",
    //     flag: "https://flagcdn.com/w20/dk.png",
    //     phoneLength: 8,
    // },
    // {
    //     code: "FI",
    //     dial_code: "+358",
    //     name: "Finland",
    //     flag: "https://flagcdn.com/w20/fi.png",
    //     phoneLength: 9,
    // }
] as const;

export type Country = typeof countries[number];
